config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  
  unauthenticated  do
    root "landing#index"
  end

  authenticated  do
    root "home#index"
  end
  get "users/password", to: "password#index"
  resources :users, only: :show do
    resources :follows, only: [:create, :destroy]
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :search, only: :index
  resources :nearby, only: :index
  resources :images, only: [:create]
  resources :notfound, only: :index
  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, foreign_key: :user_follow_id
  belongs_to :follower, foreign_key: :user_id, class_name: User.name
end

app/models/food.rb
class Food < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include AlgoliaSearch

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :images, join_table: :posts_images
  has_and_belongs_to_many :foods, join_table: :posts_foods
  has_many :likes

  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  def like user
    likes.find_by user_id: user.id
  end

  algoliasearch do
    attribute :content, :restaurant, :address, :foods, :user
  end
end

app/models/user.rb
class User < ApplicationRecord
  include AlgoliaSearch

  enum sex: [:female, :male]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :name, presence: true
         validates :sex, presence: true
         validates :date_of_birth, presence: true         
  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader

  has_many :posts
  has_many :comments
  has_many :follows
  has_many :followers, class_name: Follow.name, foreign_key: :user_follow_id
  has_many :images
  has_many :likes

  def like? post
    like = likes.find_by post_id: post.id
    like.present?
  end

  def following? user
    user = follows.find_by user_follow_id: user.id
    user.present?
  end

  def follow user
    follows.find_by user_follow_id: user.id
  end

  def newfeeds
    f_ids = follows.pluck :user_follow_id
    Post.where("user_id IN (?) OR user_id = ?", f_ids, id).order(id: :desc)
  end

  algoliasearch do
    attribute :name, :email
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.newfeeds.page(params[:page]).per 10

    @top_likes = Post.joins(:likes)
      .group("posts.id")
      .having("count(likes.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_comments = Post.joins(:comments)
      .group("posts.id")
      .having("count(comments.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_followers = User.joins(:follows)
      .group("users.id")
      .having("count(follows.user_follow_id) > 0")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .where.not(id: current_user.follow_ids)
      .limit 10
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @image = Image.new image_params.merge(user_id: current_user.id)
    if @image.save
      render json: { message: "success", id: @image.id }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end

  private
  def image_params
    params.require(:image).permit(:file)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_like, only: :destroy

  def create
    @post.likes.new user_id: current_user.id
    if @post.save
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  def destroy
    if @like.destroy
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  private
  def find_post
    @post = Post.find_by id: params[:post_id]
    unless @post
      flash[:error] = "投稿がありません"
      redirect_to notfound_index_path
    end
  end

  def find_like
    @like = @post.likes.find_by id: params[:id]
    unless @like
      flash[:error] = "「いいね」がありません"
      redirect_to notfound_index_path
    end
  end
end

app/controllers/nearby_controller.rb
class NearbyController < ApplicationController
  def index
    if params[:km].present?
      @posts = Post.near([params[:lat], params[:lng]], params[:km], units: :km).page(params[:page]).per 10
    end
    @top_likes = Post.joins(:likes)
      .group("posts.id")
      .having("count(likes.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10
    @top_followers = User.joins(:follows)
      .group("users.id")
      .having("count(follows.user_follow_id) > 0")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .where.not(id: current_user.follow_ids)
      .limit 10
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :post_params, only: [:create]
  before_action :find_post, only: [:show]

  def show
    @comments = @post.comments.order(id: :desc).page(params[:page]).per 10
  end

  def create
    @post = current_user.posts.new post_params
    @post.image_ids = params[:post][:image_ids]
    @post.food_ids = params[:post][:food_ids]
    if @post.save
      flash[:success] = "新しい投稿を投稿しました。"
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to :back
    end
  end

  private
  def post_params
    params.require(:post).permit :image_ids, :content, :restaurant, :address
  end

  def find_post
    @post = Post.find_by id: params[:id]
    unless @post
      redirect_to notfound_index_path
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    param! :query, String, default: ""
    param! :type, String, in: %w(user post), transform: :downcase, default: "user"
    param! :food_ids, String, default: "*"

    @type = params[:type]

    if params[:type] == 'user'
      @results = User.search params[:query], hitsPerPage: 10, page: params[:page]
    else
      @results = Post.search params[:query], hitsPerPage: 10, page: params[:page]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: :show

  def show
    @posts = @user.posts.order(id: :desc).page(params[:page]).per 10
  end

  private
  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:error] = "ユーザーがありません"
      redirect_to notfound_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = "Foodmate"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/nearby_helper.rb
module NearbyHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/search/users_helper.rb
module Search::UsersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/users/_header.html.erb
<div class="container">
	<div class="row">
		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="ui-block">
				<div class="top-header">
					<div class="top-header-thumb">
            <% if current_user.id == @user.id %>
              <button class="btn btn-primary btn-update-cover"><i class="fa fa-fw fa-image"></i>カバー写真の変更</button>
              <%= form_for(current_user, as: :user, url: user_registration_path, html: { method: :put, class: "d-none update-cover" }) do |f| %>
                <div class="field">
                  <%= f.file_field :cover, class: "input-cover" %>
                </div>
              <% end %>
            <% end %>
						<img src="<%= @user.cover.thumb.url %>" alt="nature">
					</div>
					<div class="profile-section">
						<div class="row">
							<div class="col-lg-5 col-md-5 ">
								<ul class="profile-menu">
									<li>
										<a href="<%= user_path @user %>" class="active">タイムライン</a>
									</li>
									<li>
										<a href="#">詳細</a>
									</li>
								</ul>
							</div>
							<div class="col-lg-5 ml-auto col-md-5">
								<ul class="profile-menu">
									<li>
										<a href="<%= user_followings_path @user %>">フォロー中</a>
									</li>
									<li>
										<a href="<%= user_followers_path @user %>">フォロワー</a>
									</li>
									<li>
                    <% unless current_user.id == @user.id %>
                      <% unless current_user.following? @user %>
                        <button class="btn btn-outline-primary btn-sm liked btn-follow" style="margin-bottom: 0"><i class="fa fa-fw fa-check"></i> Follow this user now!</button>
                        <form action="<%= user_follows_path @user %>" method="POST" class="d-none follow-form">
                          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                        </form>
                      <% else %>
                        <button class="btn btn-outline-success btn-sm text-muted btn-follow" style="margin-bottom: 0"> <i class="fa fa-fw fa-close"></i>Following!</button>
                        <form action="<%= user_follow_path @user, current_user.follow(@user) %>" method="POST" class="d-none follow-form">
                          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                          <input name="_method" type="hidden" value="delete">
                        </form>
                      <% end %>
                    <% end %>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="top-header-author">
						<a href="#" class="author-thumb" title="Click to change avatar">
							<img src="<%= @user.avatar.thumb.url %>" alt="author" class="avatar-update">
              <% if current_user.id == @user.id %>
                <%= form_for(current_user, as: :user, url: user_registration_path, html: { method: :put, class: "d-none update-avatar" }) do |f| %>
                  <div class="field">
                    <%= f.file_field :avatar, class: "input-avatar" %>
                  </div>
                <% end %>
              <% end %>
						</a>
						<div class="author-content">
							<a href="<%= user_path @user %>" class="h4 author-name"><%= @user.name %></a>
							<div class="country"><%= @user.email %></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/_left_sidebar.html.erb
<!-- Left Sidebar -->

	<div class="col-xl-3 order-xl-1 col-lg-6 order-lg-2 col-md-6 col-sm-12 col-xs-12">
		<div class="ui-block">
			<div class="ui-block-title">
				<h6 class="title">プロフィール紹介</h6>
			</div>
			<div class="ui-block-content">
				<ul class="widget w-personal-info item-block">
					<li>
						<span class="title">私について:</span>
						<span class="text"><%= @user.intro %></span>
					</li>
				</ul>

				<div class="widget w-socials">
					<h6 class="title">他のSNS:</h6>
					<a href="#" class="social-item bg-facebook">
						<i class="fa fa-facebook" aria-hidden="true"></i>
						Facebook
					</a>
					<a href="#" class="social-item bg-twitter">
						<i class="fa fa-twitter" aria-hidden="true"></i>
						Twitter
					</a>
					<a href="#" class="social-item bg-dribbble">
						<i class="fa fa-dribbble" aria-hidden="true"></i>
						Dribbble
					</a>
				</div>
			</div>
		</div>
	</div>

<!-- ... end Left Sidebar -->

app/views/users/_main_content.html.erb
<!-- Main Content -->

	<div class="col-xl-6 order-xl-2 col-lg-12 order-lg-1 col-md-12 col-sm-12 col-xs-12">
		<div id="newsfeed-items-grid">
			<% @posts.each do |post|  %>
			  <%= render "home/post", post: post %>
			<% end %>
		</div>
    <%= paginate @posts, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
	</div>

<!-- ... end Main Content -->

app/views/users/_right_sidebar.html.erb
<!-- Right Sidebar -->

		<div class="col-xl-3 order-xl-3 col-lg-6 order-lg-3 col-md-6 col-sm-12 col-xs-12">
			<div class="ui-block">
				<div class="ui-block-title">
					<h6 class="title">最近の写真</h6>
				</div>
				<div class="ui-block-content">
					<ul class="widget w-last-photo js-zoom-gallery">
              <% @user.images.order(id: :desc).page(1).per(9).each do |image| %>
                <li>
                <a href="#">
                  <img src="<%= image.file.thumb.url %>" alt="photo" class="img-responsive">
                </a>
              </li>
              <% end %>
					</ul>
				</div>
			</div>

			<div class="ui-block">
				<div class="ui-block-title">
					<h6 class="title">お気に入りのページ</h6>
				</div>

			
			</div>

		</div>

		<!-- ... end Right Sidebar -->

app/views/users/show.html.erb
<%= render "users/header" %>

<div class="container">
    <div class="row">
        <%= render "users/main_content" %>
        <%= render "users/left_sidebar" %>
        <%= render "users/right_sidebar" %>
    </div>
</div>