config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  
  unauthenticated  do
    root "landing#index"
  end

  authenticated  do
    root "home#index"
  end
  get "users/password", to: "password#index"
  resources :users, only: :show do
    resources :follows, only: [:create, :destroy]
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :search, only: :index
  resources :nearby, only: :index
  resources :images, only: [:create]
  resources :notfound, only: :index
  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, foreign_key: :user_follow_id
  belongs_to :follower, foreign_key: :user_id, class_name: User.name
end

app/models/food.rb
class Food < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include AlgoliaSearch

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :images, join_table: :posts_images
  has_and_belongs_to_many :foods, join_table: :posts_foods
  has_many :likes

  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  def like user
    likes.find_by user_id: user.id
  end

  algoliasearch do
    attribute :content, :restaurant, :address, :foods, :user
  end
end

app/models/user.rb
class User < ApplicationRecord
  include AlgoliaSearch

  enum sex: [:female, :male]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :name, presence: true
         validates :sex, presence: true
         validates :date_of_birth, presence: true         
  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader

  has_many :posts
  has_many :comments
  has_many :follows
  has_many :followers, class_name: Follow.name, foreign_key: :user_follow_id
  has_many :images
  has_many :likes

  def like? post
    like = likes.find_by post_id: post.id
    like.present?
  end

  def following? user
    user = follows.find_by user_follow_id: user.id
    user.present?
  end

  def follow user
    follows.find_by user_follow_id: user.id
  end

  def newfeeds
    f_ids = follows.pluck :user_follow_id
    Post.where("user_id IN (?) OR user_id = ?", f_ids, id).order(id: :desc)
  end

  algoliasearch do
    attribute :name, :email
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.newfeeds.page(params[:page]).per 10

    @top_likes = Post.joins(:likes)
      .group("posts.id")
      .having("count(likes.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_comments = Post.joins(:comments)
      .group("posts.id")
      .having("count(comments.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_followers = User.joins(:follows)
      .group("users.id")
      .having("count(follows.user_follow_id) > 0")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .where.not(id: current_user.follow_ids)
      .limit 10
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @image = Image.new image_params.merge(user_id: current_user.id)
    if @image.save
      render json: { message: "success", id: @image.id }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end

  private
  def image_params
    params.require(:image).permit(:file)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_like, only: :destroy

  def create
    @post.likes.new user_id: current_user.id
    if @post.save
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  def destroy
    if @like.destroy
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  private
  def find_post
    @post = Post.find_by id: params[:post_id]
    unless @post
      flash[:error] = "投稿がありません"
      redirect_to notfound_index_path
    end
  end

  def find_like
    @like = @post.likes.find_by id: params[:id]
    unless @like
      flash[:error] = "「いいね」がありません"
      redirect_to notfound_index_path
    end
  end
end

app/controllers/nearby_controller.rb
class NearbyController < ApplicationController
  def index
    if params[:km].present?
      @posts = Post.near([params[:lat], params[:lng]], params[:km], units: :km).page(params[:page]).per 10
    end
    @top_likes = Post.joins(:likes)
      .group("posts.id")
      .having("count(likes.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10
    @top_followers = User.joins(:follows)
      .group("users.id")
      .having("count(follows.user_follow_id) > 0")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .where.not(id: current_user.follow_ids)
      .limit 10
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :post_params, only: [:create]
  before_action :find_post, only: [:show]

  def show
    @comments = @post.comments.order(id: :desc).page(params[:page]).per 10
  end

  def create
    @post = current_user.posts.new post_params
    @post.image_ids = params[:post][:image_ids]
    @post.food_ids = params[:post][:food_ids]
    if @post.save
      flash[:success] = "新しい投稿を投稿しました。"
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to :back
    end
  end

  private
  def post_params
    params.require(:post).permit :image_ids, :content, :restaurant, :address
  end

  def find_post
    @post = Post.find_by id: params[:id]
    unless @post
      redirect_to notfound_index_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: :show

  def show
    @posts = @user.posts.order(id: :desc).page(params[:page]).per 10
  end

  private
  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:error] = "ユーザーがありません"
      redirect_to notfound_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = "Foodmate"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/nearby_helper.rb
module NearbyHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/_form.html.erb
<div class="ui-block">
  <div class="news-feed-form">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active inline-items" data-toggle="tab" href="#home-1" role="tab" aria-expanded="true">

          <svg class="olymp-status-icon"><use xlink:href="icons/icons.svg#olymp-status-icon"></use></svg>

          <span>投稿</span>
        </a>
      </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane active" id="home-1" role="tabpanel" aria-expanded="true">
        <form action="<%= posts_path %>" method="POST" id="new-post">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
          <div class="author-thumb">
            <img src="<%= current_user.avatar.thumb36.url %>" alt="author" width="36px">
          </div>
          <div class="form-group with-icon label-floating">
            <label class="control-label">レストランをみんなにシェアしよう！</label>
            <textarea class="form-control" placeholder="" name="post[content]"></textarea>
            <br>
            <div class="add-options-message d-none more-info">
              <div class="label-floating">
                <label class="control-label">Foods</label>
                <%= select_tag "post[food_ids]", options_from_collection_for_select(Food.all, :id, :name), class: "selectpicker form-control foods-input", multiple: "multiple" %>
              </div>
              <br>
              <div class="form-group label-floating">
                <label class="control-label">レストラン名</label>
                <input class="form-control" placeholder="" type="text" name="post[restaurant]">
              </div>
              <br>
              <div class="form-group label-floating">
                <label class="control-label">住所</label>
                <input class="form-control" placeholder="" type="text" name="post[address]">
              </div>
              <br>
            </div>
          </div>
          <div class="add-options-message">
            <a href="#" class="options-message add-photos" data-toggle="tooltip" data-placement="top"   data-original-title="写真の追加">
              <svg class="olymp-camera-icon" data-toggle="modal" data-target="#update-header-photo"><use xlink:href="icons/icons.svg#olymp-camera-icon"></use></svg>
              <span></span>
            </a>

            <a href="#" class="options-message add-more-info" data-toggle="tooltip" data-placement="top"   data-original-title="そのほかの情報の追加">
              <svg class="olymp-small-pin-icon"><use xlink:href="icons/icons.svg#olymp-small-pin-icon"></use></svg>
            </a>
            <div class="d-none file">

            </div>
            <button class="btn btn-primary btn-md-2 btn-post-status">投稿</button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
<%= render "home/popup" %>

app/views/home/_main.html.erb
<!-- Main Content -->

<main class="col-xl-6 order-xl-2 col-lg-12 order-lg-1 col-md-12 col-sm-12 col-xs-12">

  <%= render "home/form" %>

  <div id="newsfeed-items-grid">
    <% @posts.each do |post| %>
      <%= render "home/post", post: post %>
    <% end %>
  </div>
  <%= paginate @posts, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</main>

<!-- ... end Main Content -->

app/views/home/_popup.html.erb
<!-- Window-popup Update Header Photo -->

<div class="modal fade" id="update-header-photo">
  <div class="modal-dialog ui-block window-popup update-header-photo">
    <a href="#" class="close icon-close" data-dismiss="modal" aria-label="Close">
      <svg class="olymp-close-icon"><use xlink:href="icons/icons.svg#olymp-close-icon"></use></svg>
    </a>

    <div class="ui-block-title">
      <h6 class="title">Update Header Photo</h6>
    </div>

    <a href="#" class="upload-photo-item dropzone" id="image-upload" style="width: 100%" data-toggle="modal" data-target="#choose-from-my-photo">

    </a>
  </div>
</div>

app/views/home/_post.html.erb
<div class="ui-block">
  <article class="hentry post">

    <div class="post__author author vcard inline-items">
      <a href="<%= user_path post.user %>"><img src="<%= post.user.avatar.thumb36.url %>" alt="author"></a>


      <div class="author-date">
        <a class="h6 post__author-name fn" href="<%= user_path post.user %>"><%= post.user.name %>
        </a>
        <div class="post__date">
          <time class="published" datetime="2004-07-24T18:18">
            <%= time_ago_in_words post.created_at %>
          </time>
          <% if post.restaurant.present?  %>
            in restaurant
            <a href="#"><%= post.restaurant %></a> <br>
          <% end %>
          <% if post.address.present?  %>
            <i class="fa fa-fw fa-map-marker"></i> <%= post.address %> <br>
          <% end %>
        </div>
      </div>
      <% if current_user.id == post.user.id %>
        <div class="more"><svg class="olymp-three-dots-icon"><use xlink:href="/icons/icons.svg#olymp-three-dots-icon"></use></svg>
        <ul class="more-dropdown">
          <li>
            <a href="#">投稿の編集</a>
          </li>
          <li>
            <a href="#">投稿の削除</a>
          </li>
        </ul>
      </div>
      <% end %>
    </div>
    <p>
      <%= post.content %>
      <br>
      <% post.foods.each do |food| %>
        <a href="#">#<%= food.name %></a>
      <% end %>
    </p>
    <div class="post-thumb">
      <a href="<%= post_path post %>">
        <% if post.images.first %>
          <% if post.images.count > 1 %>
            <div class="more-images">+ <%= post.images.count %></div>
          <% end %>
          <img src="<%= post.images.first.file.post.url %>" alt="photo">
        <% end %>
      </a>
    </div>
    <div class="post-additional-info inline-items">

      <a href="<%= post_path post %>" class="post-add-icon inline-items">
        <svg class="olymp-heart-icon <%= "image-active" if current_user.like?(post) %>"><use xlink:href="/icons/icons.svg#olymp-heart-icon"></use></svg>
        <span class="<%= "liked" if current_user.like?(post) %>"><%= post.likes.count %></span>
      </a>

      <ul class="friends-harmonic">
        <% post.likes.order(id: :desc).limit(5).each do |like| %>
          <li>
            <a href="<%= user_path like.user %>">
              <img src="<%= like.user.avatar.thumb36.url %>" alt="friend">
            </a>
          </li>
        <% end %>
      </ul>

      <div class="names-people-likes">

        <% if current_user.like? post %>
          <a href="<%= post_path post %>">あなた</a>と
        <% else %>
          <a href="<%= post_path post %>">いいねする？</a>
        <% end %>
        <br><%= post.likes.count > 1 ? post.likes.count - 1 : 0 %>人がいいねしています
      </div>


      <div class="comments-shared">
        <a href="<%= post_path post %>" class="post-add-icon inline-items">
          <svg class="olymp-speech-balloon-icon"><use xlink:href="/icons/icons.svg#olymp-speech-balloon-icon"></use></svg>
          <span><%= post.comments.count %></span>
        </a>
      </div>


    </div>

  </article>

  <a href="<%= post_path post %>" class="more-comments">投稿を見る <span class="fa fa-fw fa-eye"></span></a>

</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">

  <%= render "home/main" %>


    <!-- Left Sidebar -->

    <aside class="col-xl-3 order-xl-1 col-lg-6 order-lg-2 col-md-6 col-sm-12 col-xs-12">
      <div class="ui-block">
        <div class="ui-block-title">
          <h6 class="title">トップ「いいね」の投稿</h6>
          <a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="icons/icons.svg#olymp-three-dots-icon"></use></svg></a>
        </div>
        <ul class="widget w-activity-feed notification-list">
          <% @top_likes.each do |post| %>
            <li>
              <div class="author-thumb">
                <img src="<%= post.user.avatar.thumb36.url %>" width="36px" alt="author">
              </div>
              <div class="notification-event">
                <a href="<%= user_path post.user %>" class="h6 notification-friend"><%= post.user.name %></a>の<a href="<%= post_path post %>" class="">投稿</a> は<%= post.likes.count %>「いいね」がある。
                <span class="notification-date"><time class="entry-date updated" datetime="2004-07-24T18:18"><%= time_ago_in_words post.created_at %></time></span>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="ui-block">
        <div class="ui-block-title">
          <h6 class="title">トップ「コメント」の投稿</h6>
          <a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="icons/icons.svg#olymp-three-dots-icon"></use></svg></a>
        </div>
        <ul class="widget w-activity-feed notification-list">
          <% @top_comments.each do |post| %>
            <li>
              <div class="author-thumb">
                <img src="<%= post.user.avatar.thumb36.url %>" width="36px" alt="author">
              </div>
              <div class="notification-event">
                <a href="<%= user_path post.user %>" class="h6 notification-friend"><%= post.user.name %></a>の<a href="<%= post_path post %>" class="">投稿</a> は<%= post.comments.count %>「コメント」がある。
                <span class="notification-date"><time class="entry-date updated" datetime="2004-07-24T18:18"><%= time_ago_in_words post.created_at %></time></span>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </aside>
    <!-- ... end Left Sidebar -->

    <aside class="col-xl-3 order-xl-3 col-lg-6 order-lg-3 col-md-6 col-sm-12 col-xs-12">

      <div class="ui-block">

        <div class="ui-block-title">
          <h6 class="title">人気がある人？</h6>
          <a href="#" class="more"><svg class="olymp-three-dots-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="icons/icons.svg#olymp-three-dots-icon"></use></svg></a>
        </div>

        <ul class="widget w-activity-feed notification-list">
          <% @top_followers.each do |user| %>
            <li>
              <div class="author-thumb">
                <img src="<%= user.avatar.thumb36.url %>" width="36px" alt="author">
              </div>
              <div class="notification-event">
                <a href="<%= user_path user %>" class=""><%=  user.name %></a> は<%= user.followers.count %>フォロー中人がいる。
              </div>
            </li>
          <% end %>
        </ul>
      </div>


    </aside>

  </div>
</div>