config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  
  unauthenticated  do
    root "landing#index"
  end

  authenticated  do
    root "home#index"
  end
  get "users/password", to: "password#index"
  resources :users, only: :show do
    resources :follows, only: [:create, :destroy]
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :search, only: :index
  resources :nearby, only: :index
  resources :images, only: [:create]
  resources :notfound, only: :index
  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, foreign_key: :user_follow_id
  belongs_to :follower, foreign_key: :user_id, class_name: User.name
end

app/models/food.rb
class Food < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include AlgoliaSearch

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :images, join_table: :posts_images
  has_and_belongs_to_many :foods, join_table: :posts_foods
  has_many :likes

  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  def like user
    likes.find_by user_id: user.id
  end

  algoliasearch do
    attribute :content, :restaurant, :address, :foods, :user
  end
end

app/models/user.rb
class User < ApplicationRecord
  include AlgoliaSearch

  enum sex: [:female, :male]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :name, presence: true
         validates :sex, presence: true
         validates :date_of_birth, presence: true         
  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader

  has_many :posts
  has_many :comments
  has_many :follows
  has_many :followers, class_name: Follow.name, foreign_key: :user_follow_id
  has_many :images
  has_many :likes

  def like? post
    like = likes.find_by post_id: post.id
    like.present?
  end

  def following? user
    user = follows.find_by user_follow_id: user.id
    user.present?
  end

  def follow user
    follows.find_by user_follow_id: user.id
  end

  def newfeeds
    f_ids = follows.pluck :user_follow_id
    Post.where("user_id IN (?) OR user_id = ?", f_ids, id).order(id: :desc)
  end

  algoliasearch do
    attribute :name, :email
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.newfeeds.page(params[:page]).per 10

    @top_likes = Post.joins(:likes)
      .group("posts.id")
      .having("count(likes.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_comments = Post.joins(:comments)
      .group("posts.id")
      .having("count(comments.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_followers = User.joins(:follows)
      .group("users.id")
      .having("count(follows.user_follow_id) > 0")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .where.not(id: current_user.follow_ids)
      .limit 10
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @image = Image.new image_params.merge(user_id: current_user.id)
    if @image.save
      render json: { message: "success", id: @image.id }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end

  private
  def image_params
    params.require(:image).permit(:file)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_like, only: :destroy

  def create
    @post.likes.new user_id: current_user.id
    if @post.save
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  def destroy
    if @like.destroy
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  private
  def find_post
    @post = Post.find_by id: params[:post_id]
    unless @post
      flash[:error] = "投稿がありません"
      redirect_to notfound_index_path
    end
  end

  def find_like
    @like = @post.likes.find_by id: params[:id]
    unless @like
      flash[:error] = "「いいね」がありません"
      redirect_to notfound_index_path
    end
  end
end

app/controllers/nearby_controller.rb
class NearbyController < ApplicationController
  def index
    if params[:km].present?
      @posts = Post.near([params[:lat], params[:lng]], params[:km], units: :km).page(params[:page]).per 10
    end
    @top_likes = Post.joins(:likes)
      .group("posts.id")
      .having("count(likes.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10
    @top_followers = User.joins(:follows)
      .group("users.id")
      .having("count(follows.user_follow_id) > 0")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .where.not(id: current_user.follow_ids)
      .limit 10
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :post_params, only: [:create]
  before_action :find_post, only: [:show]

  def show
    @comments = @post.comments.order(id: :desc).page(params[:page]).per 10
  end

  def create
    @post = current_user.posts.new post_params
    @post.image_ids = params[:post][:image_ids]
    @post.food_ids = params[:post][:food_ids]
    if @post.save
      flash[:success] = "新しい投稿を投稿しました。"
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to :back
    end
  end

  private
  def post_params
    params.require(:post).permit :image_ids, :content, :restaurant, :address
  end

  def find_post
    @post = Post.find_by id: params[:id]
    unless @post
      redirect_to notfound_index_path
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    param! :query, String, default: ""
    param! :type, String, in: %w(user post), transform: :downcase, default: "user"
    param! :food_ids, String, default: "*"

    @type = params[:type]

    if params[:type] == 'user'
      @results = User.search params[:query], hitsPerPage: 10, page: params[:page]
    else
      @results = Post.search params[:query], hitsPerPage: 10, page: params[:page]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: :show

  def show
    @posts = @user.posts.order(id: :desc).page(params[:page]).per 10
  end

  private
  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:error] = "ユーザーがありません"
      redirect_to notfound_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = "Foodmate"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/nearby_helper.rb
module NearbyHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/search/posts_helper.rb
module Search::PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/posts/show.html.erb
<div class="" id="open-photo-popup-v2" style="display: block">
  <div class="modal-dialog ui-block window-popup open-photo-popup open-photo-popup-v2">
    <div class="open-photo-thumb">

      <div class="swiper-container" data-effect="fade" data-autoplay="4000">

        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
          <!-- Slides -->
          <% @post.images.each do |image| %>
            <div class="swiper-slide">
              <div class="photo-item" data-swiper-parallax="-300" data-swiper-parallax-duration="500">
                <img src="<%= image.file.post.url %>" alt="photo">
                <div class="overlay"></div>
                <div class="content">
                  <a href="#" class="h6 title">Author: <%= @post.user.name %></a>
                  <time class="published" datetime="2017-03-24T18:18"><%= time_ago_in_words image.created_at %></time>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      </div>

      <!--Pagination tabs-->

      <div class="slider-slides">
        <% @post.images.each do |image| %>
          <a href="#" class="slides-item ">
            <img src="<%= image.file.thumb100.url %>" alt="slide">
            <div class="overlay overlay-dark"></div>
          </a>
        <% end %>
        <!--Prev Next Arrows-->

        <svg class="btn-next olymp-popup-right-arrow image-active"><use xlink:href="/icons/icons.svg#olymp-popup-right-arrow"></use></svg>

        <svg class="btn-prev olymp-popup-left-arrow image-active"><use xlink:href="/icons/icons.svg#olymp-popup-left-arrow"></use></svg>

      </div>

    </div>

    <div class="open-photo-content">

      <article class="hentry post">

        <div class="post__author author vcard inline-items">
          <img src="<%= @post.user.avatar.thumb36.url %>" alt="author">

          <div class="author-date">
            <a class="h6 post__author-name fn" href="<%= user_path @post.user %>"><%= @post.user.name %></a>
            <div class="post__date">
              <time class="published" datetime="2017-03-24T18:18">
                <%= time_ago_in_words @post.created_at %>
              </time>
            </div>
          </div>

          <% if @post.user.id == current_user.id %>
            <div class="more"><svg class="olymp-three-dots-icon"><use xlink:href="/icons/icons.svg#olymp-three-dots-icon"></use></svg>
              <ul class="more-dropdown">
                <li>
                  <a href="#">投稿の編集</a>
                </li>
                <li>
                  <a href="#">投稿の削除</a>
                </li>
              </ul>
            </div>
          <% end %>

        </div>

        <p><%= @post.content %>
          <br>
          <% @post.foods.each do |food| %>
            <a href="#">#<%= food.name %></a>
          <% end %>
        </p>

        <p>
          <% if @post.restaurant.present?  %>
            Restaurant:
            <%= @post.restaurant %> <br>
          <% end %>
          <% if @post.address.present?  %>
            In: <%= @post.address %> <br>
          <% end %>
        </p>

        <div class="post-additional-info inline-items">

          <a href="#" class="post-add-icon inline-items <%= "image-active" if current_user.like?(@post) %> btn-like">
            <svg class="olymp-heart-icon"><use xlink:href="/icons/icons.svg#olymp-heart-icon"></use></svg>
            <span class="<%= "liked" if current_user.like?(@post) %>"><%= @post.likes.count %></span>
            
            <% unless current_user.like? @post %>
              <form action="<%= post_likes_path @post %>" method="POST" class="like-form d-none">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
              </form>
            <% else %>
              <form action="<%= post_like_path @post, @post.like(current_user) %>" method="POST" class="like-form d-none">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                <input name="_method" type="hidden" value="delete">
              </form>
            <% end %>
          </a>


          <div class="comments-shared">
            <a href="#" class="post-add-icon inline-items">
              <svg class="olymp-speech-balloon-icon"><use xlink:href="/icons/icons.svg#olymp-speech-balloon-icon"></use></svg>
              <span><%= @post.comments.count %></span>
            </a>
          </div>


        </div>

      </article>

      <div class="mCustomScrollbar" data-mcs-theme="dark">
        <%= paginate @comments, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
        <ul class="comments-list">
          <% @comments.each do |comment| %>
            <li>
              <div class="post__author author vcard inline-items">
                <a href="<%= user_path comment.user %>">
                  <img src="<%= comment.user.avatar.thumb36.url %>" alt="author">
                </a>
                <div class="author-date">
                  <a class="h6 post__author-name fn" href="<%= user_path comment.user %>"><%= comment.user.name %></a>
                  <div class="post__date">
                    <time class="published" datetime="2017-03-24T18:18">
                      <%= time_ago_in_words comment.created_at %>
                    </time>
                  </div>
                </div>

                <a href="#" class="more">
                  <% if comment.user.id == current_user.id %>
                    <%= link_to post_comment_path(@post, comment),method: :delete, data: {confirm: "本当に削除したい？"}, class: "pull-right" do %>
                      <i class="fa fa-fw fa-trash"></i>
                    <% end %>
                <% end %>
                </a>

              </div>

              <p><%= comment.content %></p>
            </li>
          <% end %>
        </ul>
      </div>

      <form class="comment-form inline-items form-new-comment" action="<%= post_comments_path(@post) %>" method="POST" >

        <div class="post__author author vcard inline-items">
          <img src="<%= current_user.avatar.thumb36.url %>" alt="author">

          <div class="form-group with-icon-right ">

              <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
              <textarea class="form-control new-comment" placeholder="Enterでコメントを投稿" name="comment[content]"></textarea>

          </div>
        </div>

      </form>

    </div>

  </div>
</div>