config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  
  unauthenticated  do
    root "landing#index"
  end

  authenticated  do
    root "home#index"
  end
  get "users/password", to: "password#index"
  resources :users, only: :show do
    resources :follows, only: [:create, :destroy]
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :search, only: :index
  resources :nearby, only: :index
  resources :images, only: [:create]
  resources :notfound, only: :index
  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, foreign_key: :user_follow_id
  belongs_to :follower, foreign_key: :user_id, class_name: User.name
end

app/models/food.rb
class Food < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include AlgoliaSearch

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :images, join_table: :posts_images
  has_and_belongs_to_many :foods, join_table: :posts_foods
  has_many :likes

  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  def like user
    likes.find_by user_id: user.id
  end

  algoliasearch do
    attribute :content, :restaurant, :address, :foods, :user
  end
end

app/models/user.rb
class User < ApplicationRecord
  include AlgoliaSearch

  enum sex: [:female, :male]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :name, presence: true
         validates :sex, presence: true
         validates :date_of_birth, presence: true         
  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader

  has_many :posts
  has_many :comments
  has_many :follows
  has_many :followers, class_name: Follow.name, foreign_key: :user_follow_id
  has_many :images
  has_many :likes

  def like? post
    like = likes.find_by post_id: post.id
    like.present?
  end

  def following? user
    user = follows.find_by user_follow_id: user.id
    user.present?
  end

  def follow user
    follows.find_by user_follow_id: user.id
  end

  def newfeeds
    f_ids = follows.pluck :user_follow_id
    Post.where("user_id IN (?) OR user_id = ?", f_ids, id).order(id: :desc)
  end

  algoliasearch do
    attribute :name, :email
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.newfeeds.page(params[:page]).per 10

    @top_likes = Post.joins(:likes)
      .group("posts.id")
      .having("count(likes.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_comments = Post.joins(:comments)
      .group("posts.id")
      .having("count(comments.id) > 0")
      .order("created_at desc")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .limit 10

    @top_followers = User.joins(:follows)
      .group("users.id")
      .having("count(follows.user_follow_id) > 0")
      .where(created_at: 1.months.ago..Time.zone.now.to_date)
      .where.not(id: current_user.follow_ids)
      .limit 10
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @image = Image.new image_params.merge(user_id: current_user.id)
    if @image.save
      render json: { message: "success", id: @image.id }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end

  private
  def image_params
    params.require(:image).permit(:file)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_like, only: :destroy

  def create
    @post.likes.new user_id: current_user.id
    if @post.save
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  def destroy
    if @like.destroy
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to notfound_index_path
    end
  end

  private
  def find_post
    @post = Post.find_by id: params[:post_id]
    unless @post
      flash[:error] = "投稿がありません"
      redirect_to notfound_index_path
    end
  end

  def find_like
    @like = @post.likes.find_by id: params[:id]
    unless @like
      flash[:error] = "「いいね」がありません"
      redirect_to notfound_index_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :post_params, only: [:create]
  before_action :find_post, only: [:show]

  def show
    @comments = @post.comments.order(id: :desc).page(params[:page]).per 10
  end

  def create
    @post = current_user.posts.new post_params
    @post.image_ids = params[:post][:image_ids]
    @post.food_ids = params[:post][:food_ids]
    if @post.save
      flash[:success] = "新しい投稿を投稿しました。"
      redirect_to post_path @post
    else
      flash[:error] = "エラーがあるので、もう一度お願いします。"
      redirect_to :back
    end
  end

  private
  def post_params
    params.require(:post).permit :image_ids, :content, :restaurant, :address
  end

  def find_post
    @post = Post.find_by id: params[:id]
    unless @post
      redirect_to notfound_index_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: :show

  def show
    @posts = @user.posts.order(id: :desc).page(params[:page]).per 10
  end

  private
  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:error] = "ユーザーがありません"
      redirect_to notfound_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = "Foodmate"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/nearby_helper.rb
module NearbyHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
    toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/_header.html.erb
<!-- Header -->

<header class="header" id="site-header">

  <div class="page-title">
    <h6><a href="<%= root_path %>">フードメイト</a></h6>
  </div>

  <div class="header-content-wrapper">
    <form class="search-bar w-search notification-list friend-requests" action="<%= search_index_path%>">
      <div class="form-group with-button">
        <input type="hidden" name="type" value="<%= params[:type] == 'user' ? 'user' : 'post' %>">
        <input class="form-control js-user-search" placeholder="ユーザーや投稿の検索" type="text" name="query" value="<%= params[:query] %>">
        <button>
          <svg class="olymp-magnifying-glass-icon"><use xlink:href="/icons/icons.svg#olymp-magnifying-glass-icon"></use></svg>
        </button>
      </div>
    </form>
    <a href="<%= nearby_index_path %>" class="link-find-friend">近くのお店</a>

    <div class="control-block">

      <div class="author-page author vcard inline-items more">
        <div class="author-thumb">
          <img alt="author" src="<%= current_user.avatar.thumb36.url %>" class="avatar" width="36px">
          <span class="icon-status online"></span>
          <div class="more-dropdown more-with-triangle">
            <div class="mCustomScrollbar" data-mcs-theme="dark">
              <div class="ui-block-title ui-block-title-small">
                <h6 class="title">あなたのアカウント</h6>
              </div>

              <ul class="account-settings">
                <li>
                  <a href="<%= edit_user_registration_path %>">
                    <svg class="olymp-menu-icon"><use xlink:href="/icons/icons.svg#olymp-menu-icon"></use></svg>
                    <span>プロフィール設定</span>
                  </a>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <svg class="olymp-logout-icon"><use xlink:href="/icons/icons.svg#olymp-logout-icon"></use></svg>
                    <span>ログアウト</span>
                  <% end %>
                </li>
              </ul>

              <div class="ui-block-title ui-block-title-small">
                <h6 class="title">フードメイトについて</h6>
              </div>

              <ul>
                <li>
                  <a href="#">
                    <span>規約と条件</span>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <span>ファックス</span>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <span>経歴</span>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <span>お問い合わせ</span>
                  </a>
                </li>
              </ul>
            </div>

          </div>
        </div>
        <a href="<%= user_path current_user %>" class="author-name fn">
          <div class="author-title">
          <%= current_user.email %>   <svg class="olymp-dropdown-arrow-icon"><use xlink:href="/icons/icons.svg#olymp-dropdown-arrow-icon"></use></svg>
          </div>
          <span class="author-subtitle"><%= current_user.name %></span>
        </a>
      </div>

    </div>
  </div>

</header>

<!-- ... end Header -->


<!-- Responsive Header -->

<header class="header header-responsive" id="site-header-responsive">

  <div class="header-content-wrapper">
  </div>

  <!-- Tab panes -->
  <div class="tab-content tab-content-responsive">

    <div class="tab-pane " id="search" role="tabpanel">


      <form class="search-bar w-search notification-list friend-requests">
        <div class="form-group with-button">
          <input class="form-control js-user-search" placeholder="Search here people or pages..." type="text">
        </div>
      </form>


    </div>

  </div>
  <!-- ... end  Tab panes -->

</header>

<!-- ... end Responsive Header -->

<div class="header-spacer"></div>

app/views/layouts/_sidebar.html.erb
<!-- Fixed Sidebar Left -->

<div class="fixed-sidebar">
  <div class="fixed-sidebar-left sidebar--small" id="sidebar-left">
    <a href="<%= root_path %>" class="logo">
      <img src="<%= image_path "logo.png" %>" alt="フードメイト">
    </a>

    <div class="mCustomScrollbar" data-mcs-theme="dark">
      <ul class="left-menu">
        <li>
          <a href="#" class="js-sidebar-open">
            <svg class="olymp-menu-icon left-menu-icon"  data-toggle="tooltip" data-placement="right"   data-original-title="メニューを開く"><use xlink:href="/icons/icons.svg#olymp-menu-icon"></use></svg>
          </a>
        </li>
        <li>
          <a href="<%= root_path %>">
            <svg class="olymp-newsfeed-icon left-menu-icon" data-toggle="tooltip" data-placement="right"   data-original-title="ニュースフィード"><use xlink:href="/icons/icons.svg#olymp-newsfeed-icon"></use></svg>
          </a>
        </li>
        <% if user_signed_in? %>
          <li>
            <a href="<%= user_path current_user %>">
              <svg class="olymp-star-icon left-menu-icon"  data-toggle="tooltip" data-placement="right"   data-original-title="お気に入りのページ"><use xlink:href="/icons/icons.svg#olymp-star-icon"></use></svg>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="fixed-sidebar-left sidebar--large" id="sidebar-left-1">
    <% if user_signed_in?  %>
    <a href="<%= user_path current_user %>" class="logo">
      <img src="<%= image_path "logo.png" %>" alt="フードメイト">
      <h6 class="logo-title">olympus</h6>
    </a>
<% end  %>
    <div class="mCustomScrollbar" data-mcs-theme="dark">
      <ul class="left-menu">
        <li>
          <a href="#" class="js-sidebar-open">
            <svg class="olymp-close-icon left-menu-icon"><use xlink:href="/icons/icons.svg#olymp-close-icon"></use></svg>
            <span class="left-menu-title">メニューを閉じる</span>
          </a>
        </li>
        <li>
          <a href="<%= root_path %>">
            <svg class="olymp-newsfeed-icon left-menu-icon" data-toggle="tooltip" data-placement="right"   data-original-title="ニュースフィード"><use xlink:href="/icons/icons.svg#olymp-newsfeed-icon"></use></svg>
            <span class="left-menu-title">ニュースフィード</span>
          </a>
        </li>
        <% if user_signed_in? %>
          <li>
            <a href="<%= user_path current_user %>">
              <svg class="olymp-star-icon left-menu-icon"  data-toggle="tooltip" data-placement="right"   data-original-title="お気に入りのページ"><use xlink:href="/icons/icons.svg#olymp-star-icon"></use></svg>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!-- ... end Fixed Sidebar Left -->

<!-- Fixed Sidebar Left -->

<div class="fixed-sidebar fixed-sidebar-responsive">

  <div class="fixed-sidebar-left sidebar--small" id="sidebar-left-responsive">
    <a href="#" class="logo js-sidebar-open">
      <img src="<%= image_path "logo.png" %>" alt="フードメイト">
    </a>

  </div>

  <div class="fixed-sidebar-left sidebar--large" id="sidebar-left-1-responsive">
    <a href="#" class="logo">
      <img src="<%= image_path "logo.png" %>" alt="フードメイト">
      <h6 class="logo-title">フードメイト</h6>
    </a>

    <div class="mCustomScrollbar" data-mcs-theme="dark">

      <div class="control-block">
        <div class="author-page author vcard inline-items">
          <div class="author-thumb">
            <img alt="author" src="<%= current_user.avatar.thumb36 %>" width="36px" class="avatar">
            <span class="icon-status online"></span>
          </div>
          <a href="02-ProfilePage.html" class="author-name fn">
            <div class="author-title">
              James Spiegel <svg class="olymp-dropdown-arrow-icon"><use xlink:href="/icons/icons.svg#olymp-dropdown-arrow-icon"></use></svg>
            </div>
            <span class="author-subtitle">SPACE COWBOY</span>
          </a>
        </div>
      </div>

      <div class="ui-block-title ui-block-title-small">
        <h6 class="title">MAIN SECTIONS</h6>
      </div>

      <ul class="left-menu">
        <li>
          <a href="#" class="js-sidebar-open">
            <svg class="olymp-close-icon left-menu-icon"><use xlink:href="/icons/icons.svg#olymp-close-icon"></use></svg>
            <span class="left-menu-title">メニューを閉じる</span>
          </a>
        </li>
        <li>
          <a href="<%= root_path %>">
            <svg class="olymp-newsfeed-icon left-menu-icon" data-toggle="tooltip" data-placement="right"   data-original-title="ニュースフィード"><use xlink:href="/icons/icons.svg#olymp-newsfeed-icon"></use></svg>
            <span class="left-menu-title">ニュースフィード</span>
          </a>
        </li>
        <li>
          <a href="<%= user_path current_user %>">
            <svg class="olymp-star-icon left-menu-icon"  data-toggle="tooltip" data-placement="right"   data-original-title="お気に入りのページ"><use xlink:href="/icons/icons.svg#olymp-star-icon"></use></svg>
            <span class="left-menu-title">プロフィール</span>
          </a>
        </li>
      </ul>

      <div class="ui-block-title ui-block-title-small">
        <h6 class="title">YOUR ACCOUNT</h6>
      </div>

      <ul class="account-settings">
        <li>
          <a href="#">

            <svg class="olymp-menu-icon"><use xlink:href="/icons/icons.svg#olymp-menu-icon"></use></svg>

            <span>Profile Settings</span>
          </a>
        </li>
        <li>
          <a href="#">
            <svg class="olymp-star-icon left-menu-icon"  data-toggle="tooltip" data-placement="right"   data-original-title="FAV PAGE"><use xlink:href="/icons/icons.svg#olymp-star-icon"></use></svg>

            <span>Create Fav Page</span>
          </a>
        </li>
        <li>
          <a href="#">
            <svg class="olymp-logout-icon"><use xlink:href="/icons/icons.svg#olymp-logout-icon"></use></svg>

            <span>Log Out</span>
          </a>
        </li>
      </ul>

      <div class="ui-block-title ui-block-title-small">
        <h6 class="title">About フードメイト</h6>
      </div>

      <ul class="about-olympus">
        <li>
          <a href="#">
            <span>Terms and Conditions</span>
          </a>
        </li>
        <li>
          <a href="#">
            <span>FAQs</span>
          </a>
        </li>
        <li>
          <a href="#">
            <span>Careers</span>
          </a>
        </li>
        <li>
          <a href="#">
            <span>Contact</span>
          </a>
        </li>
      </ul>

    </div>
  </div>
</div>

<!-- ... end Fixed Sidebar Left -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all'%>
  </head>

  <body>
    <%= render "layouts/sidebar" %>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= javascript_include_tag 'application'%>
    <%= render "layouts/flash" %>
    <%= yield :map %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
  </head>

  <body class="landing-page">
    <%= yield %>
    <%= javascript_include_tag 'application'%>
    <%= render "layouts/flash" %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
  </head>

  <body class="landing-page">
  <div class="content-bg-wrap">
    <div class="content-bg"></div>
  </div>


  <!-- Landing Header -->

  <div class="container">
    <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12">
        <div id="site-header-landing" class="header-landing">
          <a href="<%= root_path %>" class="logo">
            <img src="<%= image_path "logo.png" %>" alt="Olympus">
            <h5 class="logo-title">olympus</h5>
          </a>

          <ul class="profile-menu">
            <li>
              <a href="#">私たちについて</a>
            </li>
            <li>
              <a href="#">経歴</a>
            </li>
            <li>
              <a href="#">ファックス</a>
            </li>
            <li>
              <a href="#">ヘルプサポート</a>
            </li>
            <li>
              <a href="#" class="js-expanded-menu">
                <svg class="olymp-menu-icon"><use xlink:href="/icons/icons.svg#olymp-menu-icon"></use></svg>
                <svg class="olymp-close-icon"><use xlink:href="/icons/icons.svg#olymp-close-icon"></use></svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- ... end Landing Header -->

  <!-- Login-Registration Form  -->

  <div class="container">
    <div class="row display-flex">
      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12">
        <div class="landing-content">
          <%= yield("form") %>
        </div>
      </div>

      <div class="col-xl-5 col-lg-6 col-md-12 col-sm-12 col-xs-12">
        <div class="registration-login-form">
          <%= yield %>
        </div>
        <!--login form here-->
      </div>
    </div>
  </div>
    <%= javascript_include_tag 'application'%>
    <%= render "layouts/flash" %>
  </body>
</html>